name: chortkeh
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_otp_text_field: ^1.1.0+2
  simple_animations: ^5.0.0+3
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  provider: ^6.0.5
  fluentui_system_icons: ^1.1.153
  flutter_credit_card: ^3.0.6
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  shared_preferences: 2.0.15
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  fl_chart: ^0.62.0
  circular_bottom_navigation: ^2.3.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  rive: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
  fonts:
    - family: Radin3
      fonts:
        - asset: fonts/Radin3.ttf
    - family: Kalameh
      fonts:
        - asset: fonts/Kalame/Kalameh-SemiBold.ttf
        - asset: fonts/Kalame/Kalameh-Bold.ttf
          weight: 700
    - family: Vazir
      fonts:
        - asset: fonts/Vazir/Vazir-Bold-FD-WOL.ttf
          weight: 700
        - asset: fonts/Vazir/Vazir-Light-FD-WOL.ttf
          weight: 300
        - asset: fonts/Vazir/Vazir-Medium-FD-WOL.ttf
          weight: 500
        - asset: fonts/Vazir/Vazir-Thin-FD-WOL.ttf
          weight: 100
        - asset: fonts/Vazir/Vazir-FD-WOL.ttf
#    - family: FontAwesome
#      fonts:
#        - asset: fonts/FontAwesomeIcons/fa-regular-400.ttf
#          weight: 400
#        - asset: fonts/FontAwesomeIcons/fa-brands-400.ttf
#          weight: 400
#        - asset: fonts/FontAwesomeIcons/fa-duotone-900.ttf
#          weight: 900
#        - asset: fonts/FontAwesomeIcons/fa-light-300.ttf
#          weight: 300
#        - asset: fonts/FontAwesomeIcons/fa-solid-900.ttf
#          weight: 800
#        - asset: fonts/FontAwesomeIcons/fa-thin-100.ttf
#          weight: 100
#        - asset: fonts/FontAwesomeIcons/fa-v4compatibility.ttf
  uses-material-design: true

